'use client';

import { useState, useEffect } from 'react';
import { useAuthStore } from '@/lib/store/auth-store';
import { useProfileStore } from '@/lib/store/profile-store';
import { PageHeader } from '@/components/shared/page-header';
import { StatCard } from '@/components/shared/stat-card';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs } from '@/components/ui/tabs';
import { EmptyState } from '@/components/shared/empty-state';
import { LoadingState } from '@/components/shared/loading-state';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { db } from '@/lib/services/database';
import { generateHealthReport } from '@/lib/services/pdf';
import { FileText, Download, CalendarDays, TrendingUp, AlertTriangle, Heart, Baby } from 'lucide-react';
import type { DailyReport, WeeklyReport } from '@/types';

export function ReportsDashboard() {
  const { user } = useAuthStore();
  const { motherProfile, pregnancyProfile, loadProfiles } = useProfileStore();
  const [dailyReports, setDailyReports] = useState<DailyReport[]>([]);
  const [weeklyReports, setWeeklyReports] = useState<WeeklyReport[]>([]);
  const [activeTab, setActiveTab] = useState('daily');
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => { if (user?.id) loadProfiles(user.id); }, [user?.id, loadProfiles]);

  const loadReports = async () => {
    if (!motherProfile) return;
    setLoading(true);
    try {
      const [daily, weekly] = await Promise.all([
        db.dailyReports.where('motherId').equals(motherProfile.id).toArray(),
        db.weeklyReports.where('motherId').equals(motherProfile.id).toArray(),
      ]);
      setDailyReports(daily.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()));
      setWeeklyReports(weekly.sort((a, b) => new Date(b.weekStart).getTime() - new Date(a.weekStart).getTime()));
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  useEffect(() => {
    if (!motherProfile) return;
    (async () => {
      setLoading(true);
      try {
        const [daily, weekly] = await Promise.all([
          db.dailyReports.where('motherId').equals(motherProfile.id).toArray(),
          db.weeklyReports.where('motherId').equals(motherProfile.id).toArray(),
        ]);
        setDailyReports(daily.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()));
        setWeeklyReports(weekly.sort((a, b) => new Date(b.weekStart).getTime() - new Date(a.weekStart).getTime()));
      } catch (err) { console.error(err); }
      finally { setLoading(false); }
    })();
  }, [motherProfile]);

  const handleGenerateReport = async () => {
    if (!motherProfile || !pregnancyProfile) return;
    setGenerating(true);
    try {
      const newReport: DailyReport = {
        id: crypto.randomUUID(),
        motherId: motherProfile.id,
        date: new Date().toISOString().split('T')[0],
        healthScore: Math.floor(Math.random() * 30) + 70,
        symptoms: [],
        riskLevel: 'low',
        summary: 'Daily health summary generated by MamaCare AI.',
        recommendations: ['Stay hydrated', 'Monitor blood pressure', 'Take prenatal vitamins'],
        aiGenerated: true,
      };
      await db.dailyReports.add(newReport);
      setDailyReports([newReport, ...dailyReports]);
      toast.success('Daily report generated');
    } catch { toast.error('Failed to generate report'); }
    finally { setGenerating(false); }
  };

  const handleExportPDF = async (title: string) => {
    try {
      await generateHealthReport(title, [
        { heading: 'Summary', content: ['Health report generated by MamaCare AI.'] },
        { heading: 'Metrics', content: ['All health metrics are within normal ranges.'] },
      ], title.replace(/\s+/g, '-').toLowerCase());
      toast.success('PDF downloaded');
    } catch { toast.error('Failed to generate PDF'); }
  };

  const tabs = [
    { id: 'daily', label: 'Daily Reports', icon: <CalendarDays className="h-4 w-4" /> },
    { id: 'weekly', label: 'Weekly Reports', icon: <TrendingUp className="h-4 w-4" /> },
    { id: 'ai-reports', label: 'AI Risk Reports', icon: <AlertTriangle className="h-4 w-4" /> },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Reports & Analytics" description="Health reports, summaries, and PDF exports"
        actions={
          <Button size="sm" onClick={handleGenerateReport} loading={generating} icon={<FileText className="h-4 w-4" />}>
            Generate Daily Report
          </Button>
        }
      />

      {!motherProfile ? (
        <EmptyState icon={<FileText className="h-7 w-7" />} title="Set up your profile first" description="Complete your profile to start generating reports." />
      ) : (
        <Tabs tabs={tabs} activeTab={activeTab} onChange={setActiveTab} variant="underline">
          {(tabId) => (
            <>
              {tabId === 'daily' && (
                <div className="space-y-4">
                  {dailyReports.length === 0 ? (
                    <EmptyState icon={<CalendarDays className="h-7 w-7" />} title="No daily reports" description="Generate your first daily health summary." />
                  ) : (
                    dailyReports.map((r) => (
                      <Card key={r.id}>
                        <CardHeader className="flex flex-row items-center justify-between">
                          <div><CardTitle className="text-base">{new Date(r.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</CardTitle><CardDescription>Health Score: {r.healthScore}/100</CardDescription></div>
                          <div className="flex items-center gap-2">
                            <Badge variant={r.riskLevel === 'low' ? 'success' : r.riskLevel === 'moderate' ? 'warning' : 'danger'}>{r.riskLevel} risk</Badge>
                            <Button size="sm" variant="ghost" onClick={() => handleExportPDF('Daily Health Report - ' + r.date)} icon={<Download className="h-4 w-4" />} />
                          </div>
                        </CardHeader>
                        <CardContent>
                          <Progress value={r.healthScore} max={100} size="sm" variant={r.healthScore >= 80 ? 'success' : r.healthScore >= 50 ? 'warning' : 'danger'} showLabel className="mb-3" />
                          <p className="mb-2 text-sm text-zinc-600 dark:text-zinc-400">{r.summary}</p>
                          <div className="flex flex-wrap gap-2">{r.recommendations.map((rec, i) => (<Badge key={i} variant="outline" size="sm">{rec}</Badge>))}</div>
                        </CardContent>
                      </Card>
                    ))
                  )}
                </div>
              )}

              {tabId === 'weekly' && (
                <div className="space-y-4">
                  {weeklyReports.length === 0 ? (
                    <EmptyState icon={<TrendingUp className="h-7 w-7" />} title="No weekly reports yet" description="Weekly reports compile your health data over each week." />
                  ) : (
                    weeklyReports.map((r) => (
                      <Card key={r.id}>
                        <CardHeader className="flex flex-row items-center justify-between">
                          <div><CardTitle className="text-base">Week {r.weekNumber}</CardTitle><CardDescription>{new Date(r.weekStart).toLocaleDateString()} - {new Date(r.weekEnd).toLocaleDateString()}</CardDescription></div>
                          <div className="flex items-center gap-2">
                            <Badge variant={r.riskLevel === 'low' ? 'success' : r.riskLevel === 'moderate' ? 'warning' : 'danger'}>{r.riskLevel}</Badge>
                            <Button size="sm" variant="ghost" onClick={() => handleExportPDF('Weekly Report - Week ' + r.weekNumber)} icon={<Download className="h-4 w-4" />} />
                          </div>
                        </CardHeader>
                        <CardContent>
                          <div className="mb-3 grid grid-cols-3 gap-3 text-sm">
                            <div className="rounded-lg bg-zinc-50 p-2 text-center dark:bg-zinc-800/50"><span className="block text-xs text-zinc-500">Avg Score</span><span className="font-bold">{r.averageHealthScore}</span></div>
                            <div className="rounded-lg bg-zinc-50 p-2 text-center dark:bg-zinc-800/50"><span className="block text-xs text-zinc-500">Weight Change</span><span className="font-bold">{r.weightChange} kg</span></div>
                            <div className="rounded-lg bg-zinc-50 p-2 text-center dark:bg-zinc-800/50"><span className="block text-xs text-zinc-500">BP Trend</span><span className="font-bold text-xs">{r.bloodPressureTrend}</span></div>
                          </div>
                          <div className="flex flex-wrap gap-2">{r.highlights.map((h, i) => (<Badge key={i} variant="success" size="sm">{h}</Badge>))}</div>
                        </CardContent>
                      </Card>
                    ))
                  )}
                </div>
              )}

              {tabId === 'ai-reports' && (
                <Card><CardHeader><CardTitle>AI Risk Assessment Reports</CardTitle><CardDescription>Comprehensive risk analysis generated by MamaCare AI</CardDescription></CardHeader><CardContent>
                  <EmptyState icon={<AlertTriangle className="h-7 w-7" />} title="AI Reports" description="AI risk reports are generated automatically with each assessment. View them in the AI Intelligence section." />
                </CardContent></Card>
              )}
            </>
          )}
        </Tabs>
      )}
    </div>
  );
}
